### ISSUE TITLE
Right Click -> Save Image functionality doesn't work ("Check internet connection")

### ISSUE THREAD

**Issue by JustinKaukonen** [DarthSomebody/MangaPlusPlus#1]
Hi there, I am using Chrome and just installed this script and visually it looks great, love the sidebar. That said, the main reason I installed it was for the purpose of downloading the manga pages--currently when I right click the images, I get the dialogue with 'save image as' which is great--however, when I try to download it, it immediately fails with the error 'check internet connection'. I am definitely connected to the internet--I was able to download some images from mangadex.

I tried opening the image in a new tab to see if I could download it from there instead, but it gives the error "Your file couldn’t be accessed. It may have been moved, edited, or deleted. ERR_FILE_NOT_FOUND".

I CAN copy the image directly from mangaplus and paste it into something like paint, so technically I could save it from there if I copy and paste over each page. I would definitely prefer to be able to save it without that though haha.

**Comment by kmsomebody** [comment]
I've taken a look at this issue and unfortunately I don't have a solution for this.
The images are loaded as blob and the browser can't save these.

If anyone has a solution for this, feel free to open this issue again or submit a PR.
